//设置依赖的配置文件
require.config({
	paths:{
		"jquery":"jquery-1.11.1.min",
		"hdindex":"hd_index",
		"hdlist":"hd_list",
		"hddetail":"hd_detail",
		"hdreg":"hd_reg",
		"hdlogin":"hd_login",
	}
})
//设置依赖
require(["jquery","hdindex","hdlist","hddetail","hdreg","hdlogin"],function($,ind,list,det,reg,log){
//	$("body").css("background","red")
	ind.fn();
	list.fn();
	det.fn();
	reg.fn();
	log.fn();
})
